version: "2"
services:
  app:
    image: golang:latest
    volumes:
      - .:/go-fiber
    working_dir: /go-fiber
    command: go run main.go

    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 127:0:0:1:6379:6379