version: "3.9"
services:
  api:
    image: adrienbdx/go-fiber:latest
    volumes:
      - .:/go-fiber
    working_dir: /api
    build: ./
    command: go run main.go
    ports:
      - "3333:3000"
    depends_on: 
      - redis
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 127:0:0:1:6379:6379 
