Update docker-compose.yml
2728bf7
Update compose for local
version: "3.9"
services:
  api:
    image: golang:latest
    volumes:
      - .:/go-fiber
    working_dir: /go-fiber
    build: ./
    command: go run main.go
    ports:
      - "3333:3000"
    depends_on: 
      - redis
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      #- 127:0:0:1:6379:6379 
